# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socketIOexample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MagicalRecord'
  # Pods for socketIOexample

  target 'socketIOexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
